#### Run

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
RAWS = [f for f in Path('./places').glob('*.csv') if f.is_file()]
RAW_DFS = []
for f in RAWS:
    try: RAW_DFS.append(pd.read_csv(f))
    except: RAW_DFS.append(pd.DataFrame())
df_raw = pd.concat(RAW_DFS, ignore_index=True)
df_raw.drop_duplicates(subset=['id'], inplace=True)
df_raw = df_raw[[
    "id","displayName",
    "primaryTypeDisplayName","primaryType","types",
    "rating","userRatingCount",
    "location","shortFormattedAddress",
    "priceRange","priceLevel",
    "googleMapsUri",
    "websiteUri","businessStatus",
]]

In [3]:
df_validity = pd.DataFrame({
    col: df_raw[col].notna().sum() / len(df_raw) for col in df_raw.columns
}, index=[0])
display(df_validity)
df_parsed = df_raw[df_raw['rating'].notna() & df_raw['userRatingCount'].notna()]

,id,displayName,primaryTypeDisplayName,primaryType,types,rating,userRatingCount,location,shortFormattedAddress,priceRange,priceLevel,googleMapsUri,websiteUri,businessStatus
0,1.0,1.0,1.0,1.0,1.0,0.849515,0.849515,1.0,1.0,0.703883,0.23301,1.0,0.679612,1.0

In [4]:
from type_parsing import get_summary_type, check_takeaway

df_parsed["summaryType"] = df_parsed.apply(get_summary_type, axis=1)
df_parsed["takeaway"] = df_parsed.apply(check_takeaway, axis=1)
# ── Diagnostics ───────────────────────────────────────────────────────────────
dist = df_parsed["summaryType"].value_counts()
unresolved = (df_parsed["summaryType"] == "Restaurant").sum()
print(f"Unique summaryTypes : {dist.nunique()}")
print(f"Still 'Restaurant'  : {unresolved} / {len(df_parsed)}  ({unresolved/len(df_parsed):.1%})")
# display(dist.to_frame("count"))
# for row in df_parsed[df_parsed["summaryType"]=="Ghost Kitchen"].itertuples():
#     display(row.types)
display(df_parsed[df_parsed["takeaway"]!="Dine-In"])

Unique summaryTypes : 12
Still 'Restaurant'  : 14 / 175  (8.0%)

,id,displayName,primaryTypeDisplayName,primaryType,types,rating,userRatingCount,location,shortFormattedAddress,priceRange,priceLevel,googleMapsUri,websiteUri,businessStatus,summaryType,takeaway
2,ChIJXSngkPgEdkgRaWmfsAy9ipE,Pak Hong Fish Bar,Takeout Restaurant,meal_takeaway,"['meal_delivery', 'food_delivery', 'chinese_re...",3.4,151.0,"{'latitude': 51.4736693, 'longitude': -0.1330481}","413 Wandsworth Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=10487402544486115...,https://pakhongfishbar.wixsite.com/pakhong,OPERATIONAL,Seafood,Takeaway Only
17,ChIJ7Zyh9_gEdkgRZJGEzIctdgY,Peri Peri Chicken Bites,Takeout Restaurant,meal_takeaway,"['fast_food_restaurant', 'meal_takeaway', 'res...",4.2,148.0,"{'latitude': 51.4748247, 'longitude': -0.13225...","242 Wandsworth Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=46560967275449994...,NaN,OPERATIONAL,Fast Food,Takeaway Only
22,ChIJAU_oYwAFdkgRonragj5OHLk,Pizzaverse - Halal Sourdough Pizza,Takeout Restaurant,meal_takeaway,"['halal_restaurant', 'pizza_delivery', 'fast_f...",4.9,28.0,"{'latitude': 51.474934399999995, 'longitude': ...","355 Wandsworth Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=13338622226754861...,https://www.ubereats.com/gb/store/pizzaverse/h...,OPERATIONAL,Pizza,Takeaway Only
36,ChIJ1bfdm0cFdkgRMFJ0uQStlFw,Bronson's burgers - Nine Elms,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",4.1,79.0,"{'latitude': 51.4748321, 'longitude': -0.14040...","Lindford Street Business Estate, 76 Stewart's ...","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=66711471838454298...,http://www.bronsonsburgers.co.uk/,OPERATIONAL,Burgers,Takeaway Only
49,ChIJy6HWT00FdkgR8Trw9v-oHu4,The Sushi Co Battersea,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'food', 'point...",5.0,3.0,"{'latitude': 51.475114899999994, 'longitude': ...","Unit 20C, 15, 17 Ingate Pl, London",NaN,NaN,https://maps.google.com/?cid=17158337447641234...,https://www.thesushico.co.uk/,OPERATIONAL,Japanese,Takeaway Only
51,ChIJWXUpk2wFdkgRqR14C_Z-JAQ,Joy Of Bao,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'food', 'point...",4.1,7.0,"{'latitude': 51.47538240000001, 'longitude': -...","Unit 20B, Spaces Business Centre Ingate Place,...",NaN,NaN,https://maps.google.com/?cid=29850307053277124...,https://joyofbao.com/index.php,OPERATIONAL,Chinese,Takeaway Only
52,ChIJ620nI18FdkgR9yGurvLmNMs,The Sushi Kitchen,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'food', 'point...",4.3,6.0,"{'latitude': 51.4751218, 'longitude': -0.14521...","Unit 20B, Abbey Business Centre, Spaces Busine...",NaN,NaN,https://maps.google.com/?cid=14642582218475446...,NaN,OPERATIONAL,Japanese,Takeaway Only
60,ChIJT-a8YPsFdkgRrfTt9l0UmKs,Pizza Brothers (Battersea),Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",4.7,134.0,"{'latitude': 51.4757429, 'longitude': -0.15058...","42 Battersea Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=12364655170753000...,https://www.pizzabrothers.co.uk/battersea/?mtm...,OPERATIONAL,Pizza,Takeaway Only
61,ChIJsSci6twbdkgRBHYjBRhOBAE,Chicken Run Co.,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",4.7,128.0,"{'latitude': 51.4756614, 'longitude': -0.1507638}","Good Food House, 46 Battersea Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=73269359017162244...,https://www.chickenrunco.com/?utm_source=GBP.w...,OPERATIONAL,Fast Food,Takeaway Only
63,ChIJwd-mzAcFdkgR5XQw8Aq0YxY,Pizza Guys,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",3.1,94.0,"{'latitude': 51.4754739, 'longitude': -0.1513652}","60 Battersea Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=16133310506011496...,http://pizzaguys.grub24.co.uk/,OPERATIONAL,Pizza,Takeaway Only
65,ChIJJ4o9Qp4FdkgRI09MzvIybYU,South China,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",2.1,21.0,"{'latitude': 51.4754715, 'longitude': -0.15137...","60 Battersea Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=96143967979304589...,https://grub24.co.uk/menu-south-china,OPERATIONAL,Chinese,Takeaway Only
69,ChIJPf-zRgEFdkgRjN05hcwo1ws,Pho Ta Battersea,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",4.6,454.0,"{'latitude': 51.477267, 'longitude': -0.1460226}","151 Battersea Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",PRICE_LEVEL_INEXPENSIVE,https://maps.google.com/?cid=85319551328359975...,https://www.ubereats.com/gb/store/pho-ta/Kqu00...,OPERATIONAL,Vietnamese,Takeaway Only
80,ChIJfWV6zaAFdkgRshRLJs9hc5E,Shokunin Art Sushi Delivery,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'meal_delivery', 'food_deliv...",4.9,44.0,"{'latitude': 51.4748321, 'longitude': -0.14040...","Unit 33, 1st floor, Lindford Street Business E...","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=10480828300149855...,https://shokunin-artsushi.com/,CLOSED_TEMPORARILY,Japanese,Takeaway Only
84,ChIJb6X2eQAFdkgRr_Vg4LkcXiE,Lucky Chicken,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",2.0,4.0,"{'latitude': 51.474875499999996, 'longitude': ...","Kitchen 17, Lindford Street Business Estate, 7...",NaN,NaN,https://maps.google.com/?cid=24043908357214017...,NaN,OPERATIONAL,Fast Food,Takeaway Only
87,ChIJm0SleF4FdkgRiJ7FIO5NgZE,JAPANESE YAMA SUSHI,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",5.0,1.0,"{'latitude': 51.474875499999996, 'longitude': ...","Lindford Street Business Estate, 76 Stewart's ...",NaN,NaN,https://maps.google.com/?cid=10484747092642602...,http://japaneseyamasushi.com/,CLOSED_TEMPORARILY,Japanese,Takeaway Only
89,ChIJgwv8Xz0FdkgROlvs90-syok,Panzer8,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",4.8,19.0,"{'latitude': 51.474875499999996, 'longitude': ...","Lindford Street Business Estate, 76 Stewart's ...","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=99289377879535358...,https://www.panzer8.co.uk/,OPERATIONAL,Takeout,Takeaway Only
186,ChIJnXlNFVkFdkgRsufXAHbi3mU,Noushe Joon,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'food', 'point...",5.0,8.0,"{'latitude': 51.4774126, 'longitude': -0.1480689}","Arch 65 Queen's Circus, London",NaN,NaN,https://maps.google.com/?cid=73405534391086550...,NaN,CLOSED_TEMPORARILY,Takeout,Takeaway Only
213,ChIJHQGzXxMFdkgRGWl3bKP8JsY,China Garden (Clapham),Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'food', 'point...",4.5,198.0,"{'latitude': 51.4658386, 'longitude': -0.14174...","11 North St, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=14278377447454370...,https://www.chinagardenexpress.co.uk/clapham/?...,OPERATIONAL,Chinese,Takeaway Only
215,ChIJ9yoxgBQFdkgRrYyIrsAalOc,Old Town Tandoori Indian Restaurant and Takeaway,Takeout Restaurant,meal_takeaway,"['asian_restaurant', 'meal_takeaway', 'indian_...",4.9,58.0,"{'latitude': 51.4669397, 'longitude': -0.1426597}","36b North St, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=16686991934178757...,https://oldtowntakeaway.uk/,OPERATIONAL,South Asian,Takeaway Only
217,ChIJR5Zi3m4FdkgRqquBEYp5Lws,Railway Kitchen - Clapham,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'food', 'point...",5.0,1.0,"{'latitude': 51.466935899999996, 'longitude': ...","36c North St, London",NaN,NaN,https://maps.google.com/?cid=80599649222876663...,https://deliveroo.co.uk/menu/london/clapham/ra...,OPERATIONAL,Takeout,Takeaway Only
267,ChIJAdoDSUUFdkgRPIW-WDzmXVg,RAJAH ROWING INDIAN KITCHEN CLAPHAM,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",4.6,103.0,"{'latitude': 51.460142999999995, 'longitude': ...","70 Clapham Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=63674985950330565...,http://www.rajahrowing.com/,OPERATIONAL,South Asian,Takeaway Only
268,ChIJJ1i6WXcFdkgREpV9IIZ3VQo,Zing Zing,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",3.0,38.0,"{'latitude': 51.459858, 'longitude': -0.1346891}","86 Clapham Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=74463273135410920...,https://www.zing-zing.co.uk/,OPERATIONAL,Takeout,Takeaway Only
271,ChIJ3XluOnMFdkgRDpx-VIuOp1M,Matteo's Cucina Italiana Clapham,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",4.7,12.0,"{'latitude': 51.46006810000001, 'longitude': -...","72 Clapham Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=60279433553278802...,NaN,OPERATIONAL,European,Takeaway Only
272,ChIJSXWyf04EdkgR2z4I2Dfb4sI,Yun Hua,Takeout Restaurant,meal_takeaway,"['fast_food_restaurant', 'meal_delivery', 'foo...",3.1,60.0,"{'latitude': 51.459855999999995, 'longitude': ...","86 Clapham Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=14043027620988731...,NaN,OPERATIONAL,Fast Food,Takeaway Only
275,ChIJH6fU5ZoFdkgRQe37uo_XH4U,The Breakfast Bowl,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",5.0,3.0,"{'latitude': 51.46006810000001, 'longitude': -...","72 Clapham Park Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=95926227436398134...,NaN,OPERATIONAL,Cafe & Coffee,Takeaway Only
281,ChIJY9IfdEsEdkgRxOto48I4BRw,Pizza Hut Clapham,Takeout Restaurant,meal_takeaway,"['pizza_restaurant', 'pizza_delivery', 'meal_d...",4.1,369.0,"{'latitude': 51.4552, 'longitude': -0.1393}","75 Abbeville Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",PRICE_LEVEL_MODERATE,https://maps.google.com/?cid=20190824176356505...,https://www.pizzahut.co.uk/,OPERATIONAL,Pizza,Takeaway Only
282,ChIJo0YRgisFdkgRIL9Iyj6Zf5g,Fumi Express - Japanese and Korean,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'japanese_restaurant', 'kore...",4.6,23.0,"{'latitude': 51.4552516, 'longitude': -0.13942...","95 Hambalt Rd, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",NaN,https://maps.google.com/?cid=10988670110768086...,https://www.fumiexpress.co.uk/Menu,OPERATIONAL,Korean,Takeaway Only
312,ChIJv8Qb7lEEdkgR_12CqjNoc-A,Sun Sun,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'food', 'point...",4.3,209.0,"{'latitude': 51.463396599999996, 'longitude': ...","94 Clapham High St, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",PRICE_LEVEL_MODERATE,https://maps.google.com/?cid=16173385257930874...,NaN,OPERATIONAL,Takeout,Takeaway Only
431,ChIJObH3H7YFdkgR2vXJYVGP-Xk,Moxies Fish Bar,Takeout Restaurant,meal_takeaway,"['meal_takeaway', 'restaurant', 'point_of_inte...",4.3,227.0,"{'latitude': 51.452286799999996, 'longitude': ...","Gateway House, 7 Westbury Parade, London","{'startPrice': {'currencyCode': 'GBP', 'units'...",PRICE_LEVEL_MODERATE,https://maps.google.com/?cid=87892137274859821...,http://www.moxiesfishbar.co.uk/,OPERATIONAL,Seafood,Takeaway Only

#### Save

In [5]:
print(f'{len(df_parsed)}/{len(df_raw)} rows are ready for Wilson score calculation.')
df_parsed.to_csv('./ready.csv', index=False)

175/206 rows are ready for Wilson score calculation.